# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SystemManagement-GSP
version:      0.001
version_from: lib/SystemManagement/GSP.pm
installdirs:  site
requires:
    Expect:                        0
    IO::Socket::INET:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
